name: CI with SonarCloud

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build, Test & Dependency-Check Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud analysis

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: OWASP Dependency-Check Scan
        uses: dependency-check/dependency-check-action@master
        with:
          project: 'SECURE-PIPELINE-APP'  # Name for the report
          path: '.'                    # Root of the project
          format: 'SARIF'              # For GitHub Security tab integration
          args: >
            --failOnCVSS 7             # Fail on CVSS >= 7 (high/critical)
            --enableRetired            # Include retired vulnerabilities
            --scan ./package.json      # Explicitly scan package.json

      - name: Upload Dependency-Check SARIF to GitHub
        if: always()  # Run even if scan fails to show results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: './dependency-check-report.sarif'

      - name: Run unit tests
        run: npm test -- --watchAll=false

      - name: Build the project
        run: npm run build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR analysis
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}